from pathlib import Path
import shutil,re,json
root=Path('public/games')
policy="default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'none'; base-uri 'none'; form-action 'none'; object-src 'none'"
notice='Invitation adaptation, September 2026: local-only assets, telemetry removed, silent play, touch and responsive layout fixes. Original gameplay retained.'
tap=root/'taptaptap'
shutil.copytree('/tmp/vihaan-tap-source/play',tap,dirs_exist_ok=True,ignore=shutil.ignore_patterns('sounds','favicons'))
shutil.copy('/tmp/vihaan-tap-source/LICENSE',tap/'LICENSE')
p=tap/'index.html';s=p.read_text();s=re.sub(r'<script\b[^>]*src=[\"\']https?[^>]*>.*?</script>','',s,flags=re.S);s=re.sub(r'<script\b(?![^>]*\bsrc=)[^>]*>.*?</script>','',s,flags=re.S);s=re.sub(r'<link[^>]*(?:https:|/favicons/)[^>]*>','',s);s=s.replace(' ontouchstart=""','');s=s.replace('<head>','<head><meta http-equiv="Content-Security-Policy" content="'+policy+'"><script src="../session.js"></script>');s=s.replace('</head>','<link rel="stylesheet" href="invitation.css"></head>');p.write_text('<!-- '+notice+' -->\n'+s)
p=tap/'js/habibiScript.js';s=p.read_text();s=re.sub(r'var audioPool = \{.*?audioPool.addSounds\(\);[^\n]*','// Silent invitation edition: no audio assets or autoplay.',s,flags=re.S);s=re.sub(r'\s*audioPool\.(?:playSound|stopSound)\([^)]*\);','',s);s=s.replace("element.addEventListener('click', fun, false);\n    element.addEventListener('touchstart', fun, false);","element.addEventListener('pointerdown', function(event) { event.preventDefault(); fun(event); }, false);");s=s.replace('toolsBox.gnrtRndmNum(tpblCircleWidth, (gameSpcWidth - tpblCircleWidth))','toolsBox.gnrtRndmNum(8, Math.max(8, gameSpcWidth - tpblCircleWidth - 8))').replace('toolsBox.gnrtRndmNum(tpblCircleHeight, (gmSpcHeight - tpblCircleHeight))','toolsBox.gnrtRndmNum(8, Math.max(8, gmSpcHeight - tpblCircleHeight - 8))');p.write_text('// '+notice+'\n'+s)
(tap/'invitation.css').write_text('/* '+notice+' */\nhtml,body{height:100%;touch-action:none}.admin-cp{display:none!important}.main-wrapper{height:100%;max-height:100%;box-shadow:none}button:focus-visible{outline:3px solid white;outline-offset:4px}a{pointer-events:none}.gm-menu-title{font-family:Georgia,serif;font-weight:normal;text-transform:none}.gm-menu-subtitle{font-size:16px}button{touch-action:manipulation}')
bird=root/'flappy';(bird/'js').mkdir(parents=True,exist_ok=True);(bird/'css').mkdir(exist_ok=True)
for name in ['jquery.min.js','jquery.transit.min.js','main.js']:shutil.copy(Path('/tmp/vihaan-bird-source/js')/name,bird/'js'/name)
for name in ['LICENSE','README.md']:shutil.copy(Path('/tmp/vihaan-bird-source')/name,bird/name)
p=bird/'js/main.js';s=p.read_text();s=re.sub(r'//sounds.*?//loops','// Silent invitation edition; original sound assets are not distributed.\n//loops',s,flags=re.S);s=re.sub(r'\s*//mobile browsers don.t support buzz bindOnce event.*?\n}\n\nfunction showScore', '\n   showScore();\n}\n\nfunction showScore',s,flags=re.S);s=re.sub(r'\s*sound\w+\.(?:stop|play)\(\);','',s)
s=re.sub(r"var digits = score.toString\(\).split\(''\);\s*for\(var i = 0; i < digits.length; i\+\+\)\s*elemscore.append\([^\n]+",'elemscore.text(score);',s)
s=re.sub(r"var digits = highscore.toString\(\).split\(''\);\s*for\(var i = 0; i < digits.length; i\+\+\)\s*elemscore.append\([^\n]+",'elemscore.text(highscore);',s)
s=s.replace("elemmedal.append('<img src=\"assets/medal_' + medal +'.png\" alt=\"' + medal +'\">');","elemmedal.text('★').attr('aria-label', medal + ' medal');")
s=s.replace('var pipeheight = 90;','var pipeheight = Math.min(140, flyArea * 0.36);').replace('position = 180;','position = Math.min(180, $("#flyarea").height() * 0.45);').replace('var padding = 80;','var padding = Math.min(80, flyArea * 0.18);')
s=s.replace('//space bar!','//space bar!').replace('if(e.keyCode == 32)\n   {','if(e.keyCode == 32)\n   {\n      e.preventDefault();')
s=re.sub(r'//Handle mouse down OR touch start.*?\nfunction screenClick','// Unified touch/mouse input avoids synthetic double taps.\n$("#flyarea").on("pointerdown", function(event) { if (!$(event.target).closest("#replay").length) { event.preventDefault(); screenClick(); } });\n\nfunction screenClick',s,flags=re.S)
p.write_text('// '+notice+'\n// New CSS artwork and text scores replace all original proprietary art and sound.\n'+s)
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="POLICY"><title>Safari Flyer · Floppy Bird adaptation</title><link rel="stylesheet" href="css/main.css"><script src="../session.js"></script></head><body><div id="gamecontainer"><div id="gamescreen"><div id="sky"><div id="flyarea"><div id="ceiling"></div><div id="player" class="bird animated" aria-label="Bird"><i></i></div><div id="bigscore" aria-label="Score"></div><div id="splash"><h1>Safari Flyer</h1><p>A little bird. A big adventure.</p><strong>Tap anywhere to fly</strong><small>Or press the space bar</small></div><div id="scoreboard"><h2>Lovely flying!</h2><div id="medal"></div><p>Score <span id="currentscore"></span></p><p>Best this visit <span id="highscore"></span></p><button id="replay" type="button">Try again ↻</button></div></div></div><div id="land" class="animated"><span>Fly between the green branches</span><div id="debug"></div></div></div></div><div class="boundingbox" id="playerbox"></div><div class="boundingbox" id="pipebox"></div><script src="js/jquery.min.js"></script><script src="js/jquery.transit.min.js"></script><script src="js/main.js"></script></body></html>'''
(bird/'index.html').write_text('<!-- '+notice+' -->\n'+html.replace('POLICY',policy))
for name,upstream,commitfile in [('taptaptap','https://github.com/MahdiF/taptaptap','/tmp/vihaan-tap-commit.json'),('flappy','https://github.com/nebez/floppybird','/tmp/vihaan-bird-commit.json')]:
 sha=json.loads(Path(commitfile).read_text())['sha']
 (root/name/'INVITATION-NOTICE.md').write_text('# Invitation distribution\n\nSource: '+upstream+'\n\nRevision: '+sha+'\n\n'+notice+'\n\nTap Tap Tap: uses pointer events to avoid duplicate touch/click activation. Audio files are omitted.\n\nSafari Flyer: uses Floppy Bird game logic under Apache-2.0; all original graphic and sound assets are omitted. CSS graphics and text-based score displays are original invitation adaptations. jQuery and jQuery Transit retain their upstream notices.\n')
